name: Titanic ML Pipeline

on:
  push:
    branches: [ main ]      # runs every time you push to GitHub
  schedule:
    - cron: '0 9 * * 1'    # also runs every Monday 9AM automatically

jobs:
  run-pipeline:
    runs-on: ubuntu-latest  # GitHub gives you a free server

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install libraries
      run: |
        pip install pandas numpy scikit-learn joblib

    - name: Run pipeline
      run: |
        python pipeline.py

    - name: Check accuracy
      run: |
        python -c "